CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE tbl_ceps (
    "CepID" character varying(8) NOT NULL,
    "City" character varying(50) NOT NULL,
    "State" character varying(20) NOT NULL,
    CONSTRAINT "PK_tbl_ceps" PRIMARY KEY ("CepID")
);

CREATE TABLE tbl_users (
    "UserID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(70) NOT NULL,
    "Email" character varying(50) NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_tbl_users" PRIMARY KEY ("UserID")
);

CREATE TABLE tbl_clients (
    "ClientID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "Address" character varying(70) NOT NULL,
    "NumberAddress" character varying(10) NOT NULL,
    "Country" character varying(50) NOT NULL,
    "CepId" character varying(8) NOT NULL,
    "UserID" integer NOT NULL,
    CONSTRAINT "PK_tbl_clients" PRIMARY KEY ("ClientID"),
    CONSTRAINT "FK_tbl_clients_tbl_ceps_CepId" FOREIGN KEY ("CepId") REFERENCES tbl_ceps ("CepID") ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_clients_tbl_users_UserID" FOREIGN KEY ("UserID") REFERENCES tbl_users ("UserID") ON DELETE CASCADE
);

CREATE INDEX "IX_tbl_clients_CepId" ON tbl_clients ("CepId");

CREATE INDEX "IX_tbl_clients_Name" ON tbl_clients ("Name");

CREATE INDEX "IX_tbl_clients_UserID" ON tbl_clients ("UserID");

CREATE UNIQUE INDEX "IX_tbl_users_Email" ON tbl_users ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191123143404_Add Tables', '3.0.1');

