# INSTALA SDK PARA BUILD

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build-net

WORKDIR /desafioAPI

COPY *.csproj /desafioAPI

RUN dotnet restore

COPY . /desafioAPI

RUN dotnet publish -c Release -o publish

# RUN TIME PARA EXECUÇÃO

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime

WORKDIR /desafioAPI

COPY --from=build-net /desafioAPI/publish/ .

RUN ls -al

RUN dotnet --info

ENTRYPOINT [ "dotnet",  "DesafioServiceNetAPI.dll" ] 
