version: "3"
services:
  backend:
    build: ./DesafioServiceNetAPI/.
    image: desafioapi
    ports:
      - "5001:80"
    environment:
      ConnectionStrings:DefaultConnection: "Host=78.47.19.185;Database=desafio;Username=postgres;Password=123456"
    networks: 
      - desafio
    depends_on:
      - postgres-db
    
  frontend:
    build:
      context:  ./desafioSPA/.
      args:
        api: 'http://78.47.19.185'
        port: 5001
    image: desafiospa
    networks: 
      - desafio
    ports:
      - "4200:80"
    depends_on:
      - backend
    
  postgres-db:
    build: ./Postgres/.
    image: desafiodb
    ports:
      - "5432:5432"
    networks:
      - desafio
      
networks: 
  desafio:
    driver: bridge