version: "3"
services:
  backend:
    build: ./DesafioServiceNetAPI/.
    image: srpoe/desafioapi
    ports:
      - "5000:80"
    environment:
      ConnectionStrings:DefaultConnection: "Host=192.168.99.100;Database=desafio;Username=postgres;Password=123456"
    networks: 
      - desafio
    depends_on:
      - postgres-db
    
  frontend:
    build: ./desafioSPA/.
    image: srpoe/desafiospa
    networks: 
      - desafio
    ports:
      - "4200:80"
    depends_on:
      - backend
    
  postgres-db:
    build: ./Postgres/.
    image: srpoe/desafiodb
    ports:
      - "5432:5432"
    networks:
      - desafio
      
networks: 
  desafio:
    driver: bridge